### ISSUE TITLE
Migrate to procfs 0.12.0

### ISSUE THREAD

**Issue by bpetit** [hubblo-org/scaphandre#69] opened 2021-02-03 13:28 UTC
## Problem

Procfs 0.9.0 includes breaking changes compared to 0.8.1: https://github.com/eminence/procfs/releases/tag/v0.9.0

## Solution

Adapt the powercap rapl sensor to be able to keep up with the procfs upstream.

**Comment by uggla** [comment] 2021-04-16 14:12
It would be wise to ask the author of procfs if he has still plan to change/disrupt the api. If he considers the api stable enough then we could go ahead.

**Comment by bpetit** [comment] 2021-04-17 13:57
You're right, we should start a discussion with them about that.

**Comment by eminence** [comment] 2021-05-12 04:55
HI all, procfs maintainer here.   I replied to @uggla in the issue over in my repo, but I figure I'd repeat it (and continue it) here.

The procfs API is not yet at 1.0, and so the API can still change in breaking ways.

The differences between 0.8 and 0.9 aren't that big, so I think you could remain on 0.8 if you wanted (there's actually only 1 bug fix between the two versions and I don't think you're impacted by it).

If you're concerned about the work involved, I would be happy to volunteer to do the upgrade for you, if you want.  

Let me know what you think.  Thanks!

**Comment by bpetit** [comment] 2021-05-18 07:12
Hi !

Thanks a lot for those informations. We will wait for the 1.0 then and ask you if we have issues with the upgrade :)

**Comment by rossf7** [comment] 2021-12-11 10:59
Hey,
I ran into this while I was working on https://github.com/hubblo-org/scaphandre/pull/143

The problem is the systemd cgroup driver for kubernetes uses `:` as a separator and the path gets truncated which means the container ID is missing. This was fixed in https://github.com/eminence/procfs/pull/152 

If I use a fork of 0.8.1 with just the fix it works great. Could we either upgrade or create a 0.8.2 patch release?

**Comment by eminence** [comment] 2021-12-11 21:02
My general recommendation is to upgrade to the latest procfs, but if you must remain on the v0.8.x release, then I'm happy to create a 0.8.2 that has eminence/procfs#152 cherry-picked.   Just let me know

**Comment by bpetit** [comment] 2021-12-14 15:32
I'll have a look at that, as I'm working on some [refactoring](https://github.com/hubblo-org/scaphandre/issues/74). I'll look into upgrading to procfs 1.0 through that opportunity.

**Comment by bpetit** [comment] 2021-12-16 16:19
Having a try with #144 

Seems to work fine, feel free to run tests on your sides to.

**Comment by rossf7** [comment] 2021-12-17 17:31
Thanks I tested my changes in #143 with your changes in #144 and they worked fine.

**Comment by bpetit** [comment] 2021-12-17 18:07
I think I found a bug in #144 don't rely on it too much yet. I'll try to document and fix that this week end.

**Comment by bpetit** [comment] 2021-12-21 14:07
Bug is fixed. Merged this PR in the new dev branch. I'll work on #74, then merge in dev before merging everything to main.

**Closed** 2022-06-15 09:25 UTC
Labels: enhancement, help wanted
