### ISSUE TITLE
Scaphandre does not run on Debian 12

### ISSUE THREAD

**Issue by N07070** [hubblo-org/scaphandre#365] opened 2024-02-20 17:04 UTC
## Bug description

When trying to run the debian package provided in the 1.0.0 release on a Debian 12 server, the following error happens ; 

```
➜  ~ scaphandre                                
scaphandre: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

## To Reproduce

Steps to reproduce the behavior. Something like:
1. Go to the relase page
2. Click on the debian package
3. Install it on a debian 12 up to date computer

The bug was not caught because the CI is buggy too. It sais "Run scaphandre for 10 seconds, but it only outputs the Scaphandre version. 

I've tried running the same commands as the CI to reproduce by bugs, but I indeed do have all the dependencies, and all is well on the APT side, but I still can't run scaphandre. 

See :  https://github.com/hubblo-org/scaphandre/actions/runs/7652515152/workflow#L104
```
 steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y curl
      - name: Download Debian 12 scaphandre package
        run: |
          curl -O https://s3.fr-par.scw.cloud/scaphandre/x86_64/${{ env.DEB12PKG }}
      - name: Install and run scaphandre Stdout exporter for 10 seconds
        run: |
          apt install -y ./${{ env.DEB12PKG }}
          scaphandre -V
```

## Expected behavior

Scaphandre should run.

## Environment

- Linux distribution version : 

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

- Kernel version (output of `uname -r`) [e.g. 5.4.0-54-generic]

6.1.0-13-amd64

**Comment by N07070** [comment] 2024-02-20 17:23
> The bug was not caught because the CI is buggy too. It sais "Run scaphandre for 10 seconds", but it only outputs the Scaphandre version.

This changed for the last release. I thought maybe something wrong was up with that ( and they could be a single line with `timeout 10s scaphandre --stdout` to make sure everything runs ). So the CI is not buggy, but maybe had a regression in testing ? 

I can provide a pull request to implement that little change, if need be.

---

I continued digging to find where the bug could come from. I thought maybe the docker image stayed on debian 11 ( that indeed has libssl1.0 ) and not debian 12, that switched to libssl3.0, but the CI does indeed use `  /usr/bin/docker pull debian:bookworm-slim`, so no good on that side. 

I've looked into https://github.com/hubblo-org/scaphandre/actions/runs/7872701050 and nothing seems weird on my side, it looks like I've followed all the steps and that I have all the good packages etc...

**Comment by N07070** [comment] 2024-02-20 17:38
I tried installing Rust bindings to the libssl librairies, maybe that was missing, but no chance on that side either. 

My best guest now would be to build scaphandre against the libssl3.0 lib and not the libssl1.1. But that's out of my capacities :(

**Comment by bdromard** [comment] 2024-02-22 09:36
Hello @N07070 !

I think the problem is that, presently, the Debian installer available for download on the release page was built for Debian 11. Could you try installing Scaphandre with the installer available with the following link : [Debian 12 installer](https://s3.fr-par.scw.cloud/scaphandre/x86_64/scaphandre_v1.0.0-deb12_amd64.deb) ?

I just tried it on a quick Debian 12 Docker container and I didn’t get your error. I think we just have to link the Debian 12 installer to the release page.

**Comment by N07070** [comment] 2024-02-22 14:00
Indeed, I missed the part that said : `deb11_amd64.deb`. Derp. 

It works perfectly with the link you provided. 

For the futur, are the releases of the .deb planned to be build for Bookworm, Debian 12 directly ? I'm asking because I'm writing an Ansible role for Scaphandre and I would find it nice to have the deb file downloaded directly in the role, until the day it's added to Debian's repo :crossed_fingers: .

**Comment by N07070** [comment] 2024-02-22 14:02
On a side note, it there anything I can do to update the installer's deb link on the release page ? I gather it's done by the maintainers, but maybe a pull request for the CI could be useful ?

**Comment by N07070** [comment] 2024-02-22 14:02
On a side note, it there anything I can do to update the installer's deb link on the release page ? I gather it's done by the maintainers, but maybe a pull request for the CI could be useful ?

**Comment by bdromard** [comment] 2024-02-22 14:24
No worries, we should make the Debian 12 package explicitely available for download ; as you have shown, there are clear differences between `bookworm` and `buster` due to dependencies. 

For the moment, we will build packages for the various LTS Debian distributions through the CI ; the correct packages are built, but we have not automated the distribution through GitHub releases yet. We are thinking about the best ways to distribute packages for various OSes and Linux distributions, but nothing is yet settled (we are evaluating if we should use `cargo-dist` or not). 

So, your PR proposal is much appreciated, but maybe keep it in the back of your mind for the moment until we have figured our best approach !

And thank you very much for opening this issue.

**Comment by N07070** [comment] 2024-02-22 14:34
Avec plaisir très chère ! 

Bon courage :)

**Comment by bdromard** [comment] 2024-02-22 15:20
Merci !

Added the Debian 12 package to release, so I will close this issue now.

**Closed as completed by bdromard** 2024-02-22 15:20 UTC
Labels: bug
