### ISSUE TITLE
Errors on Scaphandre during Softawere installation

### ISSUE THREAD

**Issue by lcanagui** [hubblo-org/scaphandre#320] opened 2023-05-29 13:51 UTC
## Bug description

I try to install Softawere following the [documentation](https://softawere-hackathon.gitlab.io/documentation/) on a private physical Ubuntu server. I get errors on the two Scaphandre service during the start of the docker-compose.

## To Reproduce

1. docker-compose up in the [softawere](https://gitlab.com/softawere-hackathon/softawere) repository
2. Check logs of 

```sh
$ docker logs -f softawere_scaphandre_1
Scaphandre prometheus exporter
Sending ⚡ metrics
Press CTRL-C to stop scaphandre
Got Kubernetes error: Couldn't build http client (isahc): Couldn't gather kubeconfig content. | HttpClientBuildError { message: "Couldn't gather kubeconfig content." }
scaphandre::exporters: --containers was used but scaphandre couldn't connect to any container runtime.
```
and
```sh
$ docker logs -f softawere_scaphandre-json_1
Scaphandre json exporter
Sending ⚡ metrics
thread 'main' panicked at 'ArgAction::SetTrue / ArgAction::SetFalse is defaulted', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.19/src/parser/matches/arg_matches.rs:176:14
stack backtrace:
   0:     0x5581444cd4aa - std::backtrace_rs::backtrace::libunwind::trace::ha271a8a7e1f3d4ef
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5581444cd4aa - std::backtrace_rs::backtrace::trace_unsynchronized::h85739da0352c791a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5581444cd4aa - std::sys_common::backtrace::_print_fmt::hbc6ebcfb2910b329
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5581444cd4aa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1c117e52d53614f
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5581444f155e - core::fmt::write::h25eb51b9526b8e0c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/fmt/mod.rs:1213:17
   5:     0x5581444c8595 - std::io::Write::write_fmt::ha9edec5fb1621933
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/io/mod.rs:1682:15
   6:     0x5581444cd275 - std::sys_common::backtrace::_print::hf8657cd429fc3452
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5581444cd275 - std::sys_common::backtrace::print::h41b9b18ed86f86bd
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5581444cea5f - std::panicking::default_hook::{{closure}}::h22a91871f4454152
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:267:22
   9:     0x5581444ce79b - std::panicking::default_hook::h21ddc36de0cd4ae7
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:286:9
  10:     0x5581444cf169 - std::panicking::rust_panic_with_hook::h5059419d6d59b3d0
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:688:13
  11:     0x5581444cef09 - std::panicking::begin_panic_handler::{{closure}}::h0f383c291cd78343
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:579:13
  12:     0x5581444cd95c - std::sys_common::backtrace::__rust_end_short_backtrace::h70ab22f2ad318cdd
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x5581444cec12 - rust_begin_unwind
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
  14:     0x558143e96113 - core::panicking::panic_fmt::hd1d46bcde3c61d72
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
  15:     0x5581444eecb1 - core::panicking::panic_display::hc718e237a1532649
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:147:5
  16:     0x5581444eec5b - core::panicking::panic_str::h9ce92c4159ed5520
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:131:5
  17:     0x558143e960d6 - core::option::expect_failed::h0ca670a99936f1f8
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:1924:5
  18:     0x558144470f1c - clap::parser::matches::arg_matches::ArgMatches::get_flag::he0784f5bf4be9ada
  19:     0x558143eb0c07 - scaphandre::exporters::json::JSONExporter::runner::hd7e38afefda6bc45
  20:     0x558143eb6866 - scaphandre::run::h6347a0dfee4e0351
  21:     0x558143ea178d - scaphandre::main::h1841aea5a3d3c906
  22:     0x558143e9af73 - std::sys_common::backtrace::__rust_begin_short_backtrace::h58585c47a67f82b9
  23:     0x558143e9a389 - std::rt::lang_start::{{closure}}::h60d494e22c3341a0
  24:     0x5581444c310c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h203afb3af230319a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:287:13
  25:     0x5581444c310c - std::panicking::try::do_call::hf68e87013b70f3c5
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  26:     0x5581444c310c - std::panicking::try::h040ea8f298390ba2
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  27:     0x5581444c310c - std::panic::catch_unwind::h1e17b198887a05fa
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  28:     0x5581444c310c - std::rt::lang_start_internal::{{closure}}::hfb902d8927e51b86
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:148:48
  29:     0x5581444c310c - std::panicking::try::do_call::h354e6eb41f2e7d42
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  30:     0x5581444c310c - std::panicking::try::h4a39749cd018228c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  31:     0x5581444c310c - std::panic::catch_unwind::h30bce83b8de61cca
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  32:     0x5581444c310c - std::rt::lang_start_internal::h8f7e70b1a2558118
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:148:20
  33:     0x558143ea1e15 - main
  34:     0x7fa9d4917083 - __libc_start_main
  35:     0x558143e967aa - _start
  36:                0x0 - <unknown>
```

This second error disapears if I switch from hubblo/scaphandre:dev to hubblo/scaphandre version.

## Environment
Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-149-generic x86_64)

**Comment by bpetit** [comment] 2023-05-29 14:55
This bug should be fixed in dev now (can't reproduce it with latest dev).

Could you ensure you pulled the latest dev image ?

**Comment by lcanagui** [comment] 2023-05-30 08:55
> 

With the last dev image it seems to work for the softawere_scaphandre-json_1 container. The container is created and then it stops:
```
$ docker logs -f softawere_scaphandre-json_1
Scaphandre json exporter
Sending ⚡ metrics
$
```

But for the container softawere_scaphandre_1 I get the same error:
```
$ docker logs -f softawere_scaphandre_1
Scaphandre prometheus exporter
Sending ⚡ metrics
Press CTRL-C to stop scaphandre
Got Kubernetes error: Couldn't build http client (isahc): Couldn't gather kubeconfig content. | HttpClientBuildError { message: "Couldn't gather kubeconfig content." }
scaphandre::exporters: --containers was used but scaphandre couldn't connect to any container runtime.
```

**Comment by bpetit** [comment] 2023-05-30 10:21
Just pushed a fix on dev, -t (timeout) flag was needed in the wrong way. Now not specifying -t leads to the exporter to run forever ( what you need for softawere ).

For the second error, if you don't have kubernetes / a kubelet on your machine, it's a normal warning. Do you get metrics in prometheus anyway ?

**Closed** 2023-05-30 20:32 UTC
Labels: bug
